name: Deploy Hugo site to Cloudflare Pages

on:
  push:
    branches:
      - main  # 如果你的默认分支不是 main，改成 master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true  # 拉取 PaperMod 主题
          fetch-depth: 0    # 获取完整 git 历史

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.112.4'  # PaperMod 推荐版本
          extended: true

      - name: Build
        run: hugo --minify

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: my-blog  # 改成你 Cloudflare Pages 项目的实际名字
          directory: public
